// Authentication
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

// Games info
export const RECEIVED_GAMES = 'RECEIVED_GAMES';

export const PLACES_RETRIEVAL_ERROR = 'PLACES_RETRIEVAL_ERROR';
export const PLACES_RETRIEVAL_PROGRESS = 'PLACES_RETRIEVAL_PROGRESS';
export const RECEIVED_PLACES = 'RECEIVED_PLACES';

export const CREATED_GAME = 'CREATED_GAME';
export const CREATION_FAILED = 'CREATION_FAILED';
export const CREATION_IN_PROGRESS = 'CREATION_IN_PROGRESS';

export const DELETE_GAME = 'DELETE_GAME';
export const DELETE_GAME_ERROR = 'DELETE_GAME_ERROR';
export const DELETE_GAME_PROGRESS = 'DELETE_GAME_PROGRESS';
export const REINIT_PROPS = 'REINIT_PROPS';

export const JOIN_IN_PROGRESS = 'JOIN_IN_PROGRESS';
export const JOIN_SUCCESS = 'JOIN_SUCCESS';
export const JOIN_FAILED = 'JOIN_FAILED';