// Authentication
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

// Games info
export const RECEIVED_GAMES = 'RECEIVED_GAMES';
export const RECEIVED_PLACES = 'RECEIVED_PLACES';
export const CREATED_GAME = 'CREATED_GAME';
export const CREATION_FAILED = 'CREATION_FAILED';
export const CREATION_IN_PROGRESS = 'CREATION_IN_PROGRESS';