// Authentication
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

// Games info
export const GAMES_RETRIEVED = 'RECEIVED_GAMES';
export const GAMES_RETRIEVAL_ERROR = 'GAMES_RETRIEVAL_ERROR';
export const GAMES_RETRIEVAL_IN_PROGRESS = 'GAMES_RETRIEVAL_IN_PROGRESS';

export const GAME_RETRIEVED = 'RECEIVED_GAME';
export const GAME_RETRIEVAL_ERROR = 'GAME_RETRIEVAL_ERROR';
export const GAME_RETRIEVAL_IN_PROGRESS = 'GAME_RETRIEVAL_IN_PROGRESS';

export const PLACES_RETRIEVAL_ERROR = 'PLACES_RETRIEVAL_ERROR';
export const PLACES_RETRIEVAL_PROGRESS = 'PLACES_RETRIEVAL_PROGRESS';
export const PLACES_RETRIEVED = 'PLACES_RETRIEVED';

export const CREATED_GAME = 'CREATED_GAME';
export const CREATION_FAILED = 'CREATION_FAILED';
export const CREATION_IN_PROGRESS = 'CREATION_IN_PROGRESS';

export const UPDATED_GAME = 'UPDATED_GAME';
export const UPDATE_FAILED = 'UPDATE_FAILED';
export const UPDATE_IN_PROGRESS = 'UPDATE_IN_PROGRESS';

export const DELETE_GAME = 'DELETE_GAME';
export const DELETE_GAME_ERROR = 'DELETE_GAME_ERROR';
export const DELETE_GAME_PROGRESS = 'DELETE_GAME_PROGRESS';

export const REINIT_PROPS = 'REINIT_PROPS';

export const JOIN_IN_PROGRESS = 'JOIN_IN_PROGRESS';
export const JOIN_SUCCESS = 'JOIN_SUCCESS';
export const JOIN_FAILED = 'JOIN_FAILED';

export const UNJOIN_IN_PROGRESS = 'UNJOIN_IN_PROGRESS';
export const UNJOIN_SUCCESS = 'UNJOIN_SUCCESS';
export const UNJOIN_FAILED = 'UNJOIN_FAILED';